### PR TITLE
Version 1.x Makeover (Rewrite + New Features + Bugfixes)

### LINKED ISSUE #24: Replace max values by modulo for degree
(I'm on a PR to add `hwb()` & found a bug that will be fixed by it - capping must be set for the current space prior making the loop for conversion).

0deg == 360deg right ?
So if we tolerate a maximum of 360, we have inconsistent results when converting + capping values. color-convert converts 360 to 0 so we have `hue()` returning 360 or 0 depending on the method we use. If I set hwb using 400, I get 360, but using `hue()` I get 0 cause its using hsl space (that has been converted by color-convert).

Should we stop using max for hue & use a modulo (or nothing). Cause hsl(720deg,..) is valid.
Not sure how to handle that.

Note: for my current PR I'll change max to 359 to be coherent with the "max" approch.

### LINKED ISSUE #42: Add lab space
There are nice Lab space conversion functions in [color-convert](https://github.com/harthur/color-convert) (`rgb2lab`, `lab2rgb`, etc.). But the Lab space isn’t in color.js.
Maybe it’s worth adding that API to the color? L-channel can be named `'L'` not to interfere with hsl lightness, which is lower-case `'l'`. Same with `'A'` and `'B'`.

What is the reason Lab is excluded from the color? @MoOx  @harthur.

What is possible workaround for that if Lab isn’t going to be included into color?

### LINKED ISSUE #56: Make Color objects immutable
Making `Color` objects immutable would result in a leaner API:

``` js
// Mutable
const red = Color('#ee1100')
const darkerRed = red.clone().darken(.2)
const lighterRed = red.clone().lighten(.2)
```

``` js
// Immutable
const red = Color('#ee1100')
const darkerRed = red.darken(.2)
const lighterRed = red.lighten(.2)
```

### LINKED ISSUE #67: Color.clone doesn't create equal object
``` js
var c1 = new Color();
var c2 = c1.clone();
expect(c1).toEqual(c2); // => false
```

I tracked it down, and it's the `hsw` string that doesn't match:

``` js
c1.hwbString() // => hwb(0, 0%, 100%)
c2.hwbString() // => hwb(0, 0%, 0%)
```

### LINKED ISSUE #74: Initializing from HSL and HWB producing different values
Hello, ran into this when trying to get a CSS keyword from an object initialized using HSL or HWB notations.

```
var c1 = new Color('brown');
var c2 = new Color('hsl(0, 59%, 41%)');
var c3 = new Color({h: 0, s: 59, l: 41});

```

On the first case, converting it to HSL will give the right result:

```
c1.hslString();
// "hsl(0, 59%, 41%)"
```

Trying to convert the other two won't work:

```
c2.keyword();
// undefined
c3.keyword();
// undefined
```

Comparing the RGB values you can see they are different which makes the keyword method fail:

```
c1.rgb();
// {r: 165, g: 42, b: 42}

c2.rgb();
// {r: 166, g: 43, b: 43}

c3.rgb();
// {r: 166, g: 43, b: 43}
```

### LINKED ISSUE #79: Conversion from rgbNumber back to color
`color.rgbNumber()` returns an integer, however, there is no setter `Color().rgbNumber(int)` that takes this integer to convert back to color.

What's the best way to do a round-trip for rgbNumber?

### LINKED ISSUE #82: Lightness manipulation methods fail on color('black'), except negate()
Hi, color team. This lib is great, and seems to work normally... except on any version of the color black. 

On black, if I try to lighten it, nothing changes. `lighten(0.5)` and `whiten(0.5)` fail completely on black, where they work fine on other colors, or on grey. And `darken()` works fine on white. It's just black that fails. (And I'm baffled by the results of `lightness(0.5)`, but that might be more a question of my understanding. :-)

`negate()` works, and converts it to white. `alpha(0.5)` works.

`mix()` also seems to work on black.

I've tried hard to test this thoroughly. You can see a series of experiments on this Tonic, and you can manipulate the 'source' color to see the varying results: https://tonicdev.com/xmlilley/testing-color-lib

Please let me know if I'm somehow just misunderstanding either color-theory or the API. It's certainly possible. If nothing else, this behavior is at least violating the principle-of-least-surprise for me. :-)

Is this project active, and are you taking PR's for the current branch, or only for your 1.0 milestone?

### LINKED ISSUE #83: rgb2hsl bug
compass will translate rgba(#F1F1F1, .9) into rgba(241, 241, 241, 0.9), and cssnano will compress it into hsla(0,0%,95%,.9).

However, rgb(241, 241, 241) actually equals **hsl(0,0%,94.5%)**. So I think cssnano (Qix-.color) rounded it up, but it will result in UI bug, though minor.

```
var Color = require('Color');
Color('rgba(241,241,241,.9)').hslString()
/// hsla(0, 0%, 95%, 0.9)'
```

[downstream issue: cssnano](https://github.com/ben-eb/cssnano/issues/157#issuecomment-203351365)

### PR DESCRIPTION
**Pull request by Qix-**
MAKEOVER WITH RAINBOWS AND COLORS AND SHIT

> Documentation will be updated after API is finalized. Please be mindful of this!

Here it is, the final piece of the color makeover trilogy. If you recall, I did a makeover of both [`color-string`](https://github.com/Qix-/color-string/pull/22) and [`color-convert`](https://github.com/Qix-/color-convert/pull/27) that have been generally well-received. This was the final piece.

After an increasing number of people expressing some stress over the 'quirkiness' of the API recently, I decided to finally get to it. It's been about an 8 or 9 hour ordeal, which is why I was really good at procrastinating :dancing_men:.

I do already have some things in mind for a 2.x makeover, but that's far into the future and is contingent on the evolution of `color-convert` specifically.

Without further adieu, here are all of the changes. Keep in mind this is a _complete_ re-write with a pretty good portion of the API being compatible with the 0.x releases.

### The Fun Parts (new stuff, fixes, etc.)
- (Closes #56) Completely immutable API.
- (Fixes #42) All color models from [`color-convert`](https://github.com/qix-/color-convert) are supported (using `.<model-name>()`). Try it yourself!

```javascript
Color(0xFF0000).rgb().hsl().lab().hwb().xyz().cmyk().ansi256().rgb().toString()
```

Yes, this does mean that portion of the API has changed. Please see the migrations section below.

- Main `Color` class now has swizzle-able model constructors (e.g. `Color.cmyk(10, 20, 30, 40)`, `Color.rgb([15, 67, 200])`, etc.).
- No longer performs conversion for every model on every single operation - smaller footprint and faster computation times. Not entirely sure why we were doing this to begin with, but whatever.
- (Fixes #79) Constructor now supports non-string hexadecimal RGB instantiation
- (Fixes #87) `.toString()` now returns a color string.
- Added [HCG](https://github.com/Qix-/color-convert/pull/29)-specific getters/setters.
- (Fixes #42) Added XYZ/Lab getters/setters.
- (Fixes #83, #57, #93) Added a `.round()` function that takes a number of places (default is 0) to round the internal values to. The modified `.string()` and `.percentString()` methods also take this parameter, and those methods default to 1. See notes below.
- (Fixes #82) Several API clarifications. See Migrations section below.

As well, bumping the dependencies fixes #74.

### The Not-So-Fun Parts (migration)
- **Everything is immutable**. There isn't a single fix for this if you (ab)used this library earlier on - you'll most likely be tweaking several touch points. It's for the greater good, I promise. If you already treated the library as immutable then you're probably good to go. Good tests are key here.
- All `.model()` functions (to convert to an object) must now be `.model().object()`. See notes below for justification.
- All `.modelArray()` functions must now be `.model().array()`. See notes below for justification.
- When using the `.object()` method, alpha values are now `.alpha` instead of `.a` so as to not conflict with Lab.
- If you used the internal properties of the object instead of getters, you'll need to.. not do that anymore :) Use the respective model calls (`.rgb()`, `.hsl()`, etc.) paired with `.array()` - this is because we don't store *every single* model in the object at once, but simply the last worked-with model.
- `.whiteness()` / `.blackness()` -> `.white()` / `.wblack()` (note the `w` prefix).

I want to explain this one because it doesn't feel _'great'_ but I felt like it needed to happen. We have had a couple of issues (#73 being the most definitive) that address problems with the assumed functionality of the methods.

I chose to remove the `-ness` from the names because I didn't want them being interpreted as a _characteristic_ of the color, but instead a more concrete, _'absolute'_ (if you will) property of a specific color model (akin to `.cyan()`, `.red()`, `.hue()`, etc.).

The `w` prefix was chosen for both objective and subjective reasons: it objectively conflicts with CMYK's `.black()`, and HWB subjectively isn't used as much as CMYK is (please let me know if this is an abhorrently wrong assumption). Further, we have another example of the API doing this that nobody has complained about since I took over - `.saturationl()` and `.saturationv()` for the HSV and HSL models.

Also, since this seems like a good place to mention it - in lieu of something like `.lightnessab()` for the Lab model, I just stuck with `.l()`. In the future, I hope to have something a little more consistent, but for now this works.
- Constructors with specialized keys (such as `.red`, `.green` and `.blue` for RGB instead of `.r`, `.g.` and `.b`) were removed. If this is a huge problem, please let me know. For clarity, this means you can no longer instantiate with `Color({red: 10, green: 100, blue: 150})` but instead must use `Color({r: 10, g: 100, b: 150})`.
- The model getter methods (e.g. `.rgb()`, `.hsl()`, `.keyword()`) no longer act as setters. Since everything is immutable now, such functionality is useless and only creates more overhead. Please use the `Color()` constructor directly, or use the new 'static' methods (functions) such as `Color.rgb()` directly.
- (Closes #67, #46) `.clone()` was removed since all objects are immutable. Just pass objects directly. If you _really_ need a new copy of an object, use `Color(otherColorObject)`.
- `rgbaString()` was removed. If you really need a string that forces the alpha value, please let me know and I can add something into the API. Otherwise, use `.rgbString()` and if the alpha is anything but 100% then it will include it.
- The specialized `.xxxString()` methods should move to `.xxx().string()` calls. In the case you need the RGB percent string, you may still use `.percentString()` - it will automatically convert to the RGB model. For instance, if you used `.hslString()`, you would now call `.hsl().string()`.
- `.clearer()` -> `.fade()`, because "clearer" is not at all what I thought it was personally and the API is already kind of confusing (I thought clearer meant more saturated).
- `.toJSON()` now returns the current model's representation. If you absolutely need RGB, tack on `.rgb()`. This shouldn't affect many people, if any.
- Values no longer normalize (round) when getting objects or arrays. Call `.round()` first. **If you are seeing crazy long decimals, this is why.** I wanted to be sensitive to the scientific community that is using this library to perform more mathematically sensitive operations instead of approximate stuff for web users. Most people won't have a problem with this since most people use the CSS strings.
- (Fixes #24) Initializing a `Color` object with a hue-based model (hsl, hwb, etc.) performs a rotation on the value instead of clamping it to 0-360. This is in-line with the `.hue()` getter/setter and I believe it to be the correct functionality to begin with.
- `.greyscale()` -> `.grayscale()` - if you think we should have both, please let me know :)
- (Closes #86) `.saturation()` -> `.saturationl()` (to match `.saturationv()`)

### Some Notes

So why the extra three characters for things like `.hslString()` -> `.hsl().string()`? Two reasons - one, you can now snap colors to another model if necessary. For example, if I wanted to snap a color to the nearest ANSI 256 color, I can do `Color(123, 44, 220).ansi256().rgb().object()`; two, the dependencies (e.g. [`color-string`](https://github.com/qix-/color-string)) have pretty good parity with the model names used in `color-convert`, and `color-convert` has evolved a bit since the 0.x releases of `color` to a point where we can intelligently include most models, and can future-proof new models just by updating `color-convert` in `color`'s package.json.

Further, a lot of these changes are due to the internal object no longer holding _every single conversion possible_. `color-convert` now supports [quite a lot of conversion routes](https://github.com/Qix-/color-convert#routing) and maintaining all of them here was impractical, messy and tedious.

As mentioned earlier, another win is that you're going to save quite a bit of processing time, so applications that are doing things like color manipulation on images and whatnot should benefit greatly by switching to 1.x.

### Next Steps

After this PR is approved by the community and merged, it will be published as 1.0.0.

After that, there will be a few efforts moving forward:

- Tests (of course) - I noticed comprehensive tests are lacking, and a test makeover would be beneficial in its own right.
- More transformations, and more _clarity_ as to what those transformations are.
- Color scheme support (#44)
- Color space support (maybe)

I think the first thing that should be tackled now that we will have a slightly cleaner code base is to figure out some of the hairy naming that is going on here. I would love to hear some ideas about this (feel free to drop as many tickets as you'd like) - I have some of my own, but I don't always have the best ideas!

### Feedback!

I need feedback on this as I am not a primary user of this library (admittedly I use `color-convert` more than `color` proper) so I want to make sure the *users* of this library are satisfied before I merge it in. There are a _lot_ of opinionated changes in here that I have included based on all of the tickets and pull requests I've received.

Another thing I'd like to point out - this library is edge-case hell. Making decisions that benefitted all users, use cases, and color models, elegantly and without a ton of overhead, was incredibly difficult. I've attempted this rewrite probably 4 or 5 times now, ultimately scrapping it and trying again a month or two later.

If you have any strong feelings, or even not-so-strong feelings, please let me know. I'd love to know what could be done better.

Obligatory CC list:
// @MoOx @sindresorhus @kevinsuttle @mattbasta @xml @huan086 @ooflorent @mindjuice @wmira @lapanoid @ZuBB @iamstarkov @stevemao @ericclemmons @igl @dliv 

Thanks everybody!

### CODE REVIEW

**Comment by mattbasta** [comment]
Pedantry: you should consider using trailing commas in your array and object literals.

File: index.js [hunk 1]
```diff
@@ -1,210 +1,276 @@
...
+		this.valpha = typeof result.value[channels] === 'number' ? result.value[channels] : 1;
+	} else if (obj.length) {
+		this.model = model || 'rgb';
+		channels = convert[this.model].channels;
+		var newArr = _slice.call(obj, 0, channels);
+		this.color = zeroArray(newArr, channels);
+		this.valpha = typeof obj[channels] === 'number' ? obj[channels] : 1;
+	} else if (typeof obj === 'number') {
+		// this is always RGB - can be converted later on.
+		obj &= 0xFFFFFF;
```
Comment (mattbasta) [inline index.js]: It may be worthwhile to also support an alpha channel, though I'm not sure if this is possible with hex numbers, leaning towards "probably no."

https://drafts.csswg.org/css-color/#hex-notation

File: index.js [hunk 2]
```diff
@@ -1,210 +1,276 @@
...
+		this.model = 'rgb';
+		this.color = [
+			(obj >> 16) & 0xFF,
+			(obj >> 8) & 0xFF,
+			obj & 0xFF
+		];
+		this.valpha = 1;
+	} else {
+		this.valpha = 1;
```
Comment (mattbasta) [inline index.js]: may be worthwhile to declare this once at the top and reassign it in each condition where it could be something other than `1`

File: test/index.js [hunk 3]
```diff
@@ -6,76 +6,83 @@ var Color = require('..');
...
 	ok((new Color()) instanceof Color);
+	var c = Color();
+	notStrictEqual(c.rgb(), c.rgb());
+});
+
+it('Immutability', function () {
+	var c = Color(0xFF0000);
+	ok(c !== c.rgb());
+	ok(c != c.rgb()); // eslint-disable-line eqeqeq
 });
```
Comment (mattbasta) [inline test/index.js]: What does this actually test?

**Comment by ZuBB** [comment]
> `Color(0xFF0000).rgb().hsl().lab().hwb().xyz().cmyk().ansi256().rgb().toString()`
vs
> `.xxx().string()`

I did not look into the code yet, but does they do same job?

**Comment by mattbasta** [comment]
As a matter of guaranteeing immutability and perhaps protecting the users from themselves, you might want to use `Object.freeze()` on `this` and `this.color` in the `Color` constructor

**Comment by Qix-** [comment]
> @mattvadta: Pedantry: you should consider using trailing commas in your array and object literals.

I use the XO coding style which doesn't allow them. :)

**Comment by mattbasta** [comment]
You can override that, no? Avoiding them was a Crockfordism, IIRC, because IE didn't parse JS correctly until IE8 or 9. It's really a joy to write. And ES2017 has trailing comma support for function arguments, too.

**Comment by Qix-** [comment]
> @ZuBB: I did not look into the code yet, but does they (string() vs toString()) do same job?

Yes, though `toString()` is a special method in Javascript. :) Since camel case convention isn't common throughout the API I decided to keep them as two; `string` for explicit calls and leaving `toString` available for the Javascript language.

**Comment by Qix-** [comment]
@mattbasta / cc @sindresorhus on that one (Sindre created XO). I tend to be against overriding XO rules though I'd agree that if there's a functional benefit then it should be observed.

However, I don't personally support IE 7 or 8 in anything I do, and if that is the only objective gain then I'd still err on the side of not having them.

File: test/index.js (hunk 3 above)
Comment (Qix-) [inline test/index.js]: In the old verson, these would have returned that they were equal.

File: index.js (hunk 1 above)
Comment (kevinSuttle) [inline index.js]: Not sure if this is helpful or not, but ES2015 added support for octals. https://babeljs.io/docs/learn-es2015/#binary-and-octal-literals

**Comment by ZuBB** [comment]
> You can override that, no? Avoiding them was a Crockfordism, IIRC, because IE didn't parse JS correctly until IE8 or 9. It's really a joy to write. And ES2017 has trailing comma support for function arguments, too.

I am ought to support 1 project for IE8. @mattbasta can you suggest any "compiler" that works "down"?

**Comment by mattbasta** [comment]
@ZuBB I'm not sure sure what you mean

**Comment by ZuBB** [comment]
lets assume we added that trailing comma. what tool I need to use to get this lib working in IE8?

my first guess was babel. but, honestly i do not have any experience with it. so I do not know if it can drop that trailing commas..

**Comment by Qix-** [comment]
I misread your comment, @mattbasta; that should be fine. I'm not sure what the argument is then since those browsers support non-trailing commas (as they should - could you imagine if they didn't?).

**Comment by mattbasta** [comment]
@ZuBB Any minifier will remove them. Uglify, Closure Compiler, etc. Babel will probably leave them in, actually.

@Qix- A few nice things: a.) you'll never need to fiddle with commas when moving lines around b.) you'll never accidentally paste something in and have it be a syntax error, since everything is consistent and the same c.) nerdy opinions

**Comment by mattbasta** [comment]
WRT this PR, I think it looks v.good overall

**Comment by Qix-** [comment]
@mattbasta I froze the objects :) Just required tweaking `.alpha()` a bit.

**Comment by Qix-** [comment]
Side note: I'm amazing at how well diff did at figuring out how things transformed even though it's a complete rewrite.

**Comment by ericclemmons** [comment]
> Another thing I'd like to point out - this library is edge-case hell. Making decisions that benefitted all users, use cases, and color models, elegantly and without a ton of overhead, was incredibly difficult.

Complete empathy for you, and your rationale / decisions make a lot of sense.  (For me to argue in favor of changes right now would be as silly as comma placements :D).

What's the best way to test this out in an existing project?  Is there something `npm install`-able, or is there a better way?

**Comment by Qix-** [comment]
> Complete empathy for you, and your rationale / decisions make a lot of sense.

Thank you, and glad to hear :)

> What's the best way to test this out in an existing project? Is there something `npm install`-able, or is there a better way?

```console
$ npm i Qix-/color#makeover
```

:)

**Comment by ericclemmons** [comment]
@Qix- I'm glad that `.toString()` is there, as I'm using `color` with `styled-components`, which means the colors should be automatically cast correctly.

**Comment by Qix-** [comment]
@ericclemmons Everything working okay otherwise? :)

**Comment by sindresorhus** [comment]
Generally looks good :)

> Main Color class now has swizzle-able model constructors (e.g. Color.cmyk(10, 20, 30, 40), Color.rgb([15, 67, 200]), etc.).

Not a big fan of this. We now have rest/spread, so I don't really see the use-case of this either. Pick one and stick with it. Either can be easily used. For example, if you only support an array, users can just do: `Color.cmyk(...array)`.

**Comment by mindjuice** [comment]
@sindresorhus Do I misunderstand you or did you mean:

> For example, if you **don't support passing** an array, users can just do `Color.cmyk(...array)`.

Regarding the use of spreads, not everyone is using ES2015 yet, so having these functions take an arguments list or an array still seems valuable for some people (not me...I'm using ES2015, but I know some folks who can't use it on existing projects).

The downside of adding support for both styles to the API now is that it will be hard to remove one of them later, even when "everyone" *is* using ES2015.

I suppose you could document that this library is mainly targeted at ES2015 users, but then it would be weird that it's not written in ES2015. 😄

On the other hand, if you prefer to choose one style, I think accepting individual arguments seems like the winner.  Having to pass all arguments in an array to every call isn't very nice.  Choosing one style also removes the overhead of the swizzle function on every `Color` constructor.

**Comment by sindresorhus** [comment]
@mindjuice I think this module should look forward. Users not using ES2015 can always use apply:

```js
Color.cmyk.apply(Color, array);
```

I don't think it's very common to pass an array regardless.

**Comment by mindjuice** [comment]
@sindresorhus I was going to mention `apply`, but it's kind of ugly (perhaps the price you pay for being "stuck" on ES5).

Agreed that it's probably an unusual situation to be using ES5 and have your args in an array, so I'm on board with just allowing arguments to be passed separately as I mentioned above.

Maybe this module should be written in ES2015 to be forward-looking too.

**Comment by Qix-** [comment]
@mindjuice I know of a lot of projects at a few companies that rely on this module and are still forced to use 0.10 or 0.12, and babel is annoying to set up just for a few dependencies. I'll probably stick to ES5, though I agree that swizzle isn't all that necessary.

**Comment by mindjuice** [comment]
@Qix- You don't need to distribute the code in ES2015 format.  Lots of projects do a build and then just distribute the generated ES5 on npm.

Leaving it ES5 though is totally fine though, especially since you've already done the work (thanks for that BTW!). 😄

**Comment by ericclemmons** [comment]
<details><summary>@Qix- I removed `.clone()` and `.hexString()` from my code and the colors + stories (we use React Storybook) worked the same!</summary>

```diff
diff --git a/package.json b/package.json
index ca2d601..437c27b 100644
--- a/package.json
+++ b/package.json
@@ -92,7 +92,7 @@
     "body-parser": "1.15.2",
     "classnames": "2.2.5",
     "clipboard": "1.5.12",
-    "color": "0.11.4",
+    "color": "github:qix-/color#makeover",
     "common-tags": "1.3.1",
     "compression": "1.6.2",
     "connect-redis": "3.1.0",
diff --git a/src/components/QuickDegreeFinder/Button.js b/src/components/QuickDegreeFinder/Button.js
index a900f50..2e17f39 100644
--- a/src/components/QuickDegreeFinder/Button.js
+++ b/src/components/QuickDegreeFinder/Button.js
@@ -4,7 +4,7 @@ import contrast from "./contrast";
 import eh from "./eh";

 export default styled.button`
-  background: ${(props) => props.theme.ctaColor.hexString()};
+  background: ${(props) => props.theme.ctaColor};
   border: none;
   border-radius: 3px;
   box-shadow: 0 ${eh(-1)}px 0 rgba(0, 0, 0, 0.2) inset;
@@ -22,6 +22,6 @@ export default styled.button`
   }

   &:hover {
-    background: ${(props) => props.theme.ctaColor.clone().darken(0.2).hexString()};
+    background: ${(props) => props.theme.ctaColor.darken(0.2)};
   }
 `;
diff --git a/src/components/QuickDegreeFinder/Fieldset.js b/src/components/QuickDegreeFinder/Fieldset.js
index c113db6..06ed8f3 100644
--- a/src/components/QuickDegreeFinder/Fieldset.js
+++ b/src/components/QuickDegreeFinder/Fieldset.js
@@ -1,7 +1,7 @@
 import styled from "styled-components";

 export default styled.fieldset`
-  background: ${(props) => props.theme.backgroundColor.hexString()};
+  background: ${(props) => props.theme.backgroundColor};
   border: none;
   border-bottom: 1px solid rgba(0, 0, 0, 0.15);
   box-sizing: border-box;
diff --git a/src/components/QuickDegreeFinder/Form.js b/src/components/QuickDegreeFinder/Form.js
index 25f24de..93ef3dc 100644
--- a/src/components/QuickDegreeFinder/Form.js
+++ b/src/components/QuickDegreeFinder/Form.js
@@ -4,11 +4,11 @@ import eh from "./eh";

 export default styled.form`
   align-items: stretch;
-  background: ${(props) => props.theme.backgroundColor.hexString()};
+  background: ${(props) => props.theme.backgroundColor};
   background-image: ${(props) => `
     linear-gradient(
-      ${props.theme.backgroundColor.hexString()} 0px,
-      ${props.theme.backgroundColor.clone().darken(0.1).hexString()} 100%
+      ${props.theme.backgroundColor} 0px,
+      ${props.theme.backgroundColor.darken(0.1)} 100%
     )
   `};
   border-radius: 3px;
diff --git a/src/components/QuickDegreeFinder/Legend.js b/src/components/QuickDegreeFinder/Legend.js
index 451bf18..45ab11c 100644
--- a/src/components/QuickDegreeFinder/Legend.js
+++ b/src/components/QuickDegreeFinder/Legend.js
@@ -4,7 +4,7 @@ import contrast from "./contrast";
 import eh from "./eh";

 export default styled.legend`
-  background: ${(props) => props.theme.titleColor.hexString()};
+  background: ${(props) => props.theme.titleColor};
   border-top-left-radius: 3px;
   border-top-right-radius: 3px;
   box-sizing: border-box;
```
</details>

**Comment by Qix-** [comment]
@mindjuice That's fair. I might consider doing that in the future :)

@ericclemmons glad to hear :D 🎉 💃 

I might remove the swizzle support since if someone _really_ needs it later we can make an additive change instead of a breaking change.

**Comment by Qix-** [comment]
Thank you everyone!

~[:lipstick:](https://media.giphy.com/media/l0MYxef0mpdcnQnvi/source.gif)

**Comment by Qix-** [comment]
Published as `1.0.0`!

**Comment by ajoslin** [comment]
Immutability + toString() is all I care about, and it will make life a lot easier. Thank @Qix-!
